<?xml version="1.0"?>
<robot name="stella" xmlns:xacro="http://www.ros.org/wiki/xacro">
	<xacro:property name="PI" value="3.1415926535897931"/>
	
	<xacro:property name="bodyHeight" value="0.125"/>
	<xacro:property name="bodyLength" value="0.38"/>
	<xacro:property name="bodyWidth" value="0.3"/>
	<xacro:property name="bodyMass" value="10"/> 
	<xacro:property name="bodyToFloorHeight" value="0.0325"/>

	<xacro:property name="casterRadius" value="0.05175"/>
	<xacro:property name="casterMass" value="0.2"/>
	
	<xacro:property name="wheelWidth" value="0.038"/>
	<xacro:property name="wheelRadius" value="0.0725"/>
	<xacro:property name="wheelPos" value="0.05"/>
	<xacro:property name="wheelMass" value="1"/>

	<xacro:include filename="$(find stella_description)/urdf/macros.xacro"/>
	<xacro:include filename="$(find stella_description)/urdf/materials.xacro"/>
	<xacro:include filename="$(find stella_description)/urdf/stella.gazebo"/>

	<link name="base_footprint"/>
	
	<joint name="base_joint" type="fixed">
		<parent link="base_footprint"/>
		<child link="base_link"/>
	</joint>


	<link name="base_link">
		<visual>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
			</geometry>
			<material name="grey"/>
		</visual>
		
		<collision>
			<origin xyz="0 0 ${wheelRadius}" rpy="0 0 0"/>
			<geometry>
				<box size="${bodyLength} ${bodyWidth} ${bodyHeight}"/>
			</geometry>
		</collision>
 <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="8.2573504e-01"/>
      <inertia ixx="2.2124416e-03" ixy="-1.2294101e-05" ixz="3.4938785e-05"
               iyy="2.1193702e-03" iyz="-5.0120904e-06"
               izz="2.0064271e-03" />
    </inertial>

	</link>

<joint name="caster_joint" type="fixed">
  <parent link="base_link"/>
  <child link="caster_wheel"/>
</joint>

<link name="caster_wheel">
  <collision>
    <origin xyz="${-wheelRadius - 0.02 + bodyLength/2} 0 ${-bodyHeight / 2 + bodyToFloorHeight + wheelRadius}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${wheelRadius}"/>
    </geometry>
  </collision>
  
  <visual>
    <origin xyz="${-wheelRadius - 0.02 + bodyLength/2} 0 ${-bodyHeight / 2 + bodyToFloorHeight +  wheelRadius}" rpy="0 0 0"/>
    <geometry>
      <sphere radius="${wheelRadius}"/>
    </geometry>
    <material name="black"/>
  </visual>

  <inertial>
    <origin xyz="${-wheelRadius - 0.02 + bodyLength/2} 0 ${-bodyHeight / 2 + bodyToFloorHeight + wheelRadius}" rpy="0 0 0"/>
    <mass value="${casterMass}"/>
    <sphere_inertia m="${casterMass}" r="${casterRadius}"/>
  </inertial>
</link>

<wheel lr="left" tY="1"/>
<wheel lr="right" tY="-1"/>

 <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="-0.032 0 0.068" rpy="0 0 0"/>
  </joint>

  <link name="imu_link"/>

  <joint name="scan_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_scan"/>
    <origin xyz="0.135 0 ${bodyHeight + bodyToFloorHeight + 0.015}" rpy="0 0 3.14 "/>
  </joint>

  <link name="base_scan">
    <visual>
      <origin xyz="0 0 0.0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://stella_description/meshes/sensors/lds.stl" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="dark"/>
    </visual>

    <collision>
      <origin xyz="0.015 0 -0.0065" rpy="0 0 0"/>
      <geometry>
        <cylinder length="0.0315" radius="0.055"/>
      </geometry>
    </collision>

    <inertial>
      <mass value="0.114" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001" />
    </inertial>
  </link>

			
</robot>
